# Generated by Django 4.0.4 on 2022-12-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytable',
            name='img',
            field=models.ImageField(blank=True, upload_to='polls/static'),
        ),
    ]
